#!/usr/bin/env node
// Fetches the canonical SPEC.md from Brand-Context-Protocol/spec and writes:
//   src/pages/spec/v{version}.md   — versioned spec page
//   src/pages/spec/index.astro     — redirect to latest version
//
// Usage:
//   node scripts/sync-spec.mjs                     # fetch from GitHub (dev/CI builds)
//   node scripts/sync-spec.mjs --source <path>     # read from local file (GitHub Action)
//
// On fetch failure the script exits 0 so offline builds still work from committed files.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SPEC_URL = 'https://raw.githubusercontent.com/Brand-Context-Protocol/spec/main/SPEC.md';

async function getSpec() {
  const flag = process.argv.indexOf('--source');
  if (flag !== -1) {
    return readFileSync(process.argv[flag + 1], 'utf8');
  }
  const specUrl = new URL(SPEC_URL);
  specUrl.searchParams.set(
    'build',
    process.env.CF_PAGES_COMMIT_SHA ?? process.env.VERCEL_GIT_COMMIT_SHA ?? String(Date.now()),
  );
  const res = await fetch(specUrl, { cache: 'no-store' });
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching SPEC.md`);
  return res.text();
}

async function main() {
  const spec = await getSpec();

  const versionMatch = spec.match(/\*\*Version:\*\*\s+(\d+\.\d+)/);
  if (!versionMatch) throw new Error('Could not parse version from SPEC.md');
  const version = versionMatch[1];
  const statusMatch = spec.match(/\*\*Status:\*\*\s+([^\n]+)/);
  const status = statusMatch?.[1]?.trim().toLowerCase() ?? '';

  mkdirSync(join(ROOT, 'src/pages/spec'), { recursive: true });

  // Write versioned spec page
  const specPage =
    `---\nlayout: ../../layouts/Layout.astro\ntitle: BCP v${version} Specification\ndescription: Normative specification for Brand Context Protocol v${version}\n---\n\n` +
    `<a href="https://github.com/Brand-Context-Protocol/spec/issues/new" style="display:block; margin-bottom: 40px; font-family:var(--mono); font-size: 13px;">✎ Propose a change</a>\n\n` +
    spec;

  const versionedPath = join(ROOT, `src/pages/spec/v${version}.md`);
  if (existsSync(versionedPath)) {
    const existing = readFileSync(versionedPath, 'utf8');
    if (existing !== specPage && status !== 'draft') {
      const err = new Error(
        `refusing to overwrite src/pages/spec/v${version}.md — published version pages are immutable ` +
        `(they're cited externally, e.g. in IANA well-known URI registration). ` +
        `If v${version} of SPEC.md genuinely changed, bump the Version field in SPEC.md instead.`
      );
      err.fatal = true;
      throw err;
    }
    if (existing !== specPage) {
      writeFileSync(versionedPath, specPage);
      console.log(`[sync-spec] updated draft src/pages/spec/v${version}.md`);
    } else {
      console.log(`[sync-spec] src/pages/spec/v${version}.md unchanged, skipping write`);
    }
  } else {
    writeFileSync(versionedPath, specPage);
    console.log(`[sync-spec] wrote src/pages/spec/v${version}.md`);
  }

  // A website PR can land alongside a newer spec PR before GitHub's main branch
  // reflects that version. Never let a build-time fetch move /spec backwards.
  const publishedVersions = readdirSync(join(ROOT, 'src/pages/spec'))
    .map((name) => name.match(/^v(\d+)\.(\d+)\.md$/))
    .filter(Boolean)
    .map((match) => ({ version: `${match[1]}.${match[2]}`, major: Number(match[1]), minor: Number(match[2]) }))
    .sort((a, b) => b.major - a.major || b.minor - a.minor);
  const latestVersion = publishedVersions[0]?.version ?? version;

  // Update the /spec redirect to point to latest
  const indexPage = `---
// Auto-generated by scripts/sync-spec.mjs — do not edit manually
---
<html>
  <head>
    <meta http-equiv="refresh" content="0;url=/spec/v${latestVersion}" />
    <script>window.location.replace('/spec/v${latestVersion}');</script>
  </head>
  <body>
    <p>Redirecting to <a href="/spec/v${latestVersion}">BCP v${latestVersion} Specification</a>...</p>
  </body>
</html>
`;

  writeFileSync(join(ROOT, 'src/pages/spec/index.astro'), indexPage);
  console.log(`[sync-spec] /spec → v${latestVersion}`);
}

main().catch(err => {
  if (err.fatal) {
    console.error('[sync-spec] FATAL:', err.message);
    process.exit(1);
  }
  console.error('[sync-spec] warning: could not sync spec —', err.message);
  console.error('[sync-spec] using committed spec files as fallback');
  process.exit(0);
});
