#!/usr/bin/env node
// Fetches the canonical SPEC.md from Brand-Context-Protocol/spec and writes:
//   src/pages/spec/v{version}.md   — versioned spec page
//   src/pages/spec/index.astro     — redirect to latest version
//
// Usage:
//   node scripts/sync-spec.mjs                     # fetch from GitHub (dev/CI builds)
//   node scripts/sync-spec.mjs --source <path>     # read from local file (GitHub Action)
//
// On fetch failure the script exits 0 so offline builds still work from committed files.

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SPEC_URL = 'https://raw.githubusercontent.com/Brand-Context-Protocol/spec/main/SPEC.md';

async function getSpec() {
  const flag = process.argv.indexOf('--source');
  if (flag !== -1) {
    return readFileSync(process.argv[flag + 1], 'utf8');
  }
  const res = await fetch(SPEC_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching SPEC.md`);
  return res.text();
}

async function main() {
  const spec = await getSpec();

  const versionMatch = spec.match(/\*\*Version:\*\*\s+(\d+\.\d+)/);
  if (!versionMatch) throw new Error('Could not parse version from SPEC.md');
  const version = versionMatch[1];

  mkdirSync(join(ROOT, 'src/pages/spec'), { recursive: true });

  // Write versioned spec page
  const specPage =
    `---\nlayout: ../../layouts/Layout.astro\ntitle: BCP v${version} Specification\ndescription: Normative specification for Brand Context Protocol v${version}\n---\n\n` +
    `<a href="https://github.com/Brand-Context-Protocol/spec/issues/new" style="display:block; margin-bottom: 40px; font-family:var(--mono); font-size: 13px;">✎ Propose a change</a>\n\n` +
    spec;

  writeFileSync(join(ROOT, `src/pages/spec/v${version}.md`), specPage);
  console.log(`[sync-spec] wrote src/pages/spec/v${version}.md`);

  // Update the /spec redirect to point to latest
  const indexPage = `---
// Auto-generated by scripts/sync-spec.mjs — do not edit manually
---
<html>
  <head>
    <meta http-equiv="refresh" content="0;url=/spec/v${version}" />
    <script>window.location.replace('/spec/v${version}');</script>
  </head>
  <body>
    <p>Redirecting to <a href="/spec/v${version}">BCP v${version} Specification</a>...</p>
  </body>
</html>
`;

  writeFileSync(join(ROOT, 'src/pages/spec/index.astro'), indexPage);
  console.log(`[sync-spec] /spec → v${version}`);
}

main().catch(err => {
  console.error('[sync-spec] warning: could not sync spec —', err.message);
  console.error('[sync-spec] using committed spec files as fallback');
  process.exit(0);
});
